language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install -U -r requirements.txt"
  - "pip install -U -r test-requirements.txt"
script:
  - "python setup.py flake8"
  - "python setup.py nosetests"
notifications:
  email: false
  # This is Colin's instance of Homu, in the future
  # we'll move this to a production cluster.
  webhooks: http://escher.verbum.org:54856/travis
